Public Module SquishmallowNames
    Public ReadOnly Names As IReadOnlyList(Of String) =
        New List(Of String) From
        {
            "Aaliyah the Celestial Shark",
            "Aarin the Alpaca",
            "Aaron the Dragon",
            "Abbitt the Tapir",
            "Abby the Octopus",
            "Abdul the Griffin",
            "Abe the Bearded Dragon",
            "Abel the Manatee",
            "Abelita the Appaloosa",
            "Abena the Succulent",
            "Abilene the Ostrich",
            "Ace the Unicorn",
            "Achim the Lion",
            "Ada the Cow",
            "Adabelle the Strawberry Frog",
            "Adam the Pterodactyl",
            "Adderley the Sloth",
            "Addison the Lamb",
            "Adela the Basset Hound",
            "Adelaide the Octopus",
            "Adelle the Lava Lamp",
            "Adila the Antelope",
            "Adin the Space Game",
            "Adjani the Cow",
            "Adrian the Walkman",
            "Adrina the Caticorn",
            "Adrie the Caticorn",
            "Adrienne the Cactus",
            "Aegi the Sakura Dragon",
            "Aerope the Swamp Monster",
            "Agnolo the Tadpole",
            "Agnes Rose the Ostrich",
            "Agora the Witch",
            "Afiyah the Succulent",
            "Aicha the Shell",
            "Aiden the Dragon",
            "Aidy the Whale Shark",
            "Aika the Axolotl",
            "Aimee the Chick",
            "Aina the Unicorn",
            "Ainhoca the Armored Dino",
            "Ainsley the Fox",
            "Aja the Alicorn",
            "Akilah the Stingray",
            "Akina the Axolotl",
            "Akira the Sloth",
            "Aksel the Axolotl",
            "Alan the Fox",
            "Alandy the Poison Dart Frog",
            "Alba the Mushroom",
            "Alberta the Maple Latte",
            "Albinia the Dog",
            "Aldea the Axolotl",
            "Alder the Owl",
            "Aldice the Red Panda",
            "Aldous the Bat",
            "Aldron the Plague Doctor",
            "Ale the Seal",
            "Alec the Loch Ness Monster",
            "Alejandra the Bunny",
            "Aleka the Axolotl",
            "Alessi the Fox",
            "Alex the Bulldog",
            "Alex the Crab",
            "Alexie the Cow",
            "Alfred the Reindeer",
            "Alice the Llama-Pegacorn",
            "Aligail the Cupcake",
            "Alijoon the Monster",
            "Alita the SeaCow",
            "Alizeh the Fox",
            "Allina the Squirrel",
            "Ally the Axolotl",
            "Allegra the Choc. Frappe",
            "Aloeen the Latte",
            "Alonzo the Highland Cow",
            "Alphonso the Monster",
            "Alsace Lorraine the Jester",
            "Alten the Christmas Milk",
            "Althea the Axolotl",
            "Altman the Squid",
            "Alva the Coffin",
            "Alvarez the Alien",
            "Alvie the Top",
            "Alyssa the Swan",
            "Amal the Moth",
            "Amala the Axolotl",
            "Amalie the Snake",
            "Amanda the Bunny",
            "Amandine the Macaron",
            "Amara the Yeti",
            "Amaro the Hyena",
            "Amaryllis the Raccoon",
            "Ambergris the Goblin",
            "Amberjack the Fish Taco",
            "Amelie the Strawberry Milk",
            "Amiah the Narwhal",
            "Amideus the Dinosaur",
            "Amil the T-Rex",
            "Amina the Squirrel",
            "Amir the Water Buffalo",
            "Amity the Snake",
            "Amleth the Yeti",
            "Amor the Unicorn",
            "Amparo the Chicken",
            "Analea the Caticorn",
            "Analia the Unicorn",
            "Anara the Asparagus",
            "Anastasia the Axolotl",
            "Anca the Unicorn",
            "Anders the Chick",
            "Andreina the Butterfly",
            "Andres the Sheltie",
            "Andrew the Jackalope",
            "Androu the Squirrel",
            "Andy the Christmas Tree",
            "Aneira the Pegacorn",
            "Anessa the Sugar Skull",
            "Aneta the Lobster",
            "Angelica the Froz. Yogurt",
            "Angelie the Koala",
            "Angelie the Unicorn",
            "Angie the Shiba Inu",
            "Angusan the TV",
            "Anh Dao the Dodo Bird",
            "Anica the Unicorn",
            "Aniceta the Cow",
            "Aniela the Coffee Maker",
            "Anita the Cinnamon Roll",
            "Anjara the Bfast Burrito",
            "Anjali the Elephant",
            "Ankur the Mushroom",
            "Anna the Dinosaur",
            "Annalise the Alicorn",
            "Anneli the Ferret",
            "Annette the Milkshake",
            "Anni the Jellyfish",
            "Anouk the Unicorn",
            "Anoushka the Parakeet",
            "Ansel the Chips",
            "Anthony the Luchador",
            "Antjuan the Sea Monster",
            "Antoine the Peanut Butter",
            "Antonella the Cheetah",
            "Antoni the Sea Turtle",
            "Antonina the Unicorn",
            "Anu the Otter",
            "Anya the Caticorn-Mermaid",
            "Aphrodite the Dog",
            "Apollo the Firefly",
            "Apple the Bat",
            "Aqua the Sloth",
            "Aquitaine the Pig",
            "Arabella the Lamb",
            "Araminta the Caticorn",
            "Aranya the Spider",
            "Archer the Alligator",
            "Archie the Axolotl (SG)",
            "Arco the Hermit Crab",
            "Arella the Owl",
            "Argie the Grape Jelly",
            "Ari the Dinosaur",
            "Ari the Leopard",
            "Aria the Unicorn",
            "Ariana the Witch",
            "Arianna the Fox",
            "Arilla the Armadillo",
            "Arlene the Christmas Milk",
            "Arlie the Dinosaur",
            "Armie the Cow",
            "Armand the Swamp Monster",
            "Armando the Carnotaurus",
            "Arnel the Popcorn",
            "Arnold the Sheep Dog",
            "Aron the Gorilla",
            "Arona the Butterfly",
            "Arthur the Alligator",
            "Artin the Loch Ness Monster",
            "Arturo the Watermelon",
            "Ascott the Squirrel",
            "Ash the Otter",
            "Asher the Narwhal",
            "Ashley the Apple (SG)",
            "Ashlyn the Cheetah Fairy",
            "Asley the Vulture",
            "Astra the Chick",
            "Astrid the Unicorn",
            "Astrud the Bigfoot",
            "Atlas the Unicorn",
            "Atoosa the Tiger",
            "Atwater the Monster",
            "Aubrey the Avocado",
            "Auggie the Cuttlefish",
            "August the Alpaca",
            "Augustine the Bulldog",
            "Augusto the Triceratops",
            "Aurora the Unicorn",
            "Aurura the Owl",
            "Austin the Avocado",
            "Autumn the Cat",
            "Autumn the Fox",
            "Ava the Avocado",
            "Ava the Chick",
            "Avana the Axolotl",
            "Avery the Mallard Duck",
            "Avi the Mango Boba",
            "Avrill the Dragon",
            "Axel the Beetle",
            "Axiel the Chameleon",
            "Azi the Shark",
            "Aziza the Stingray",
            "Azizbek the Red Onion",
            "Azizi the Dragon"
        }.Select(Function(x) x.ToUpper).ToList
    ReadOnly Property Count As Integer
        Get
            Return Names.Count
        End Get
    End Property
End Module
